ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
DEBUG_ENABLE = yes

OLED_ENABLE = yes
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
QUANTUM_PAINTER_LVGL_INTEGRATION = yes

SRC += lvgl_helpers.c \
       display.c